version: '3.9'
services:
  homer-dev:
    container_name: homer-kasthack-dev
    hostname: homer-kasthack-dev
    image: b4bz/homer
    restart: unless-stopped
    ports:
       - 8080:8080
    environment:
       - TZ=Europe/Moscow
       - INIT_ASSETS=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./assets:/www/assets
      - ./assets/manifest.json:/www/default-assets/manifest.json
  homer-prod:
    container_name: homer-kasthack-prod
    hostname: homer-kasthack-prod
    image: kasthackphoenix/kasthack-com-homer
    build: .
    restart: unless-stopped
    ports:
       - 8081:8080
    environment:
       - TZ=Europe/Moscow
       - INIT_ASSETS=0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro